# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      tests/commonmark/commonmark\.json|
      .*\.xml|
      tests/.*\.txt
    )$

repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
    - id: check-manifest
      args: [--no-build-isolation]
      additional_dependencies: [setuptools>=46.4.0]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==21.3.1]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    - id: mypy
      args: [--config-file=setup.cfg]
      additional_dependencies:
      - myst-parser~=0.14.0
      files: >
        (?x)^(
            myst_nb/parser.py|
        )$

  # this is not used for now,
  # since it converts myst-nb to myst_nb and removes comments
  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v1.17.0
  #   hooks:
  #   - id: setup-cfg-fmt
